////PRODUTOS
export const FETCH_PRODUTOS = "FETCH_PRODUTOS";
export const FETCH_PRODUTOS_ID = "FETCH_PRODUTOS_ID";
export const FETCH_PRODUTOS_SUCCESS = "FETCH_PRODUTOS_SUCCESS";
export const FETCH_PRODUTOS_BY_ID_SUCCESS = "FETCH_PRODUTOS_BY_ID_SUCCESS";

//UPDATE PRODUTOS
export const UPDATE_PRODUTO_SUCCESS = "UPDATE_PRODUTO_SUCCESS";
export const UPDATE_PRODUTO_FAIL = "UPDATE_PRODUTO_FAIL";

///LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

//PRODFAKE
export const FETCH_PRODUTOS_FAKE = "FETCH_PRODUTOS_FAKE";
export const FETCH_PRODUTO_FAKE_ID = "FETCH_PRODUTO_FAKE_ID";
export const FETCH_PRODUTOS_FAKE_SUCCESS = "FETCH_PRODUTOS_FAKE_SUCCESS";
export const FETCH_PRODUTOS_FAKE_BY_ID_SUCCESS = "FETCH_PRODUTOS_FAKE_BY_ID_SUCCESS";





