export const FETCH_PRODUTOS = "FETCH_PRODUTOS";
export const FETCH_PRODUTOS_ID = "FETCH_PRODUTOS_ID";
export const FETCH_PRODUTOS_SUCCESS = "FETCH_PRODUTOS_SUCCESS";
export const FETCH_PRODUTOS_BY_ID_SUCCESS = "FETCH_PRODUTOS_BY_ID_SUCCESS";

