////PRODUTOS
export const FETCH_PRODUTOS = "FETCH_PRODUTOS";
export const FETCH_PRODUTOS_ID = "FETCH_PRODUTOS_ID";
export const FETCH_PRODUTOS_SUCCESS = "FETCH_PRODUTOS_SUCCESS";
export const FETCH_PRODUTOS_BY_ID_SUCCESS = "FETCH_PRODUTOS_BY_ID_SUCCESS";

///LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";



